apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dan-it-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Charizmatik/dan-it-devops-diploma.git
    targetRevision: main
    path: final-submission/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dan-it-backend
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
