apiVersion: apps/v1
kind: Deployment
metadata:
  name: dan-it-backend
  namespace: dan-it-backend
  labels:
    app.kubernetes.io/name: dan-it-backend
    app.kubernetes.io/part-of: dan-it-diploma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dan-it-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dan-it-backend
        app.kubernetes.io/part-of: dan-it-diploma
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: mikoladolia/dan-it-backend:sha-0929737f769984ce211911747c7158aa4480d2e6
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APP_VERSION
              value: sha-0929737f769984ce211911747c7158aa4480d2e6
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
